name: Main Workflow

on:
  workflow_dispatch:

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60  # enough time to cancel manually

  merge-pr-on-dispatch-success:
    runs-on: ubuntu-latest
    needs: [deploy-and-test]
    if: ${{ needs.deploy-and-test.result == 'success' }}
    steps:
      - run: exit 0  # use 1 to test failure

  resume-flux:
    name: Resume Flux (Inline)
    needs: [merge-pr-on-dispatch-success]
    if: always()
    uses: ./.github/workflows/resume-flux.yml
    with:
      reason: "main workflow: merge-pr completed (success/failure/cancelled)"
      delay_seconds: 60