name: Resume Flux on Cancel

on:
  workflow_run:
    workflows: ["Main Workflow"]
    types: [completed]

jobs:
  resume-flux:
    if: ${{ github.event.workflow_run.conclusion == 'cancelled' }}
    uses: ./.github/workflows/resume-flux.yml
    with:
      reason: "workflow_run: main workflow was cancelled"